org.gradle.jvmargs = -Xmx4G
org.gradle.parallel= true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version = 1.20.2
yarn_mappings = 1.20.2+build.4
fabric_loader_version = 0.18.4

# Mod Properties
mod_name = FrostedLib
mod_version = 1.1.1+1.20.2
maven_group = com.github.futurefrost
archives_base_name = FrostedLib

# Dependencies
fabric_api_version = 0.91.6+1.20.2
apoli_version = 2.11.11
origins_version = v1.12.10
reach_version = 2.4.0
breathing_lib_version = 01269c3
mod_menu_version = 8.0.1
cardinal_components_version=5.3.0